apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: ${kubernetes_image}:${kubernetes_version}
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --cloud-provider=aws
    - --cloud-config=/etc/kubernetes/cloud.cfg
    - --leader-elect=true
    - --service-account-private-key-file=/etc/secrets/kubeapi-key.pem
    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
    - name: certs
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: cloud-config
      mountPath: /etc/cloud.cfg
      readOnly: true
  volumes:
  - name: secrets
    hostPath:
      path: /run/kubelet
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: cloud-config
    hostPath:
      path: /etc/kubernetes/cloud.cfg
