---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v15
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: true
    version: v15
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v15
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: true
        version: v15
    spec:
      dnsPolicy: Default
      containers:
        - name: kubedns
          image: gcr.io/google_containers/kubedns-amd64:1.3
          ports:
          - name: dns-local
            containerPort: 10053
            protocol: UDP
          - name: dns-tcp-local
            containerPort: 10053
            protocol: TCP
          args:
          - --domain=cluster.local.
          - --dns-port=10053
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 50Mi
        - name: dnsmasq
          image: gcr.io/google_containers/kube-dnsmasq-amd64:1.3
          args:
          - --cache-size=1000
          - --no-resolv
          - --server=127.0.0.1#10053
          ports:
          - name: dns
            containerPort: 53
            protocol: UDP
          - name: dns-tcp
            containerPort: 53
            protocol: TCP
        - name: healthz
          image: gcr.io/google_containers/exechealthz-amd64:1.0
          ports:
          - containerPort: 8080
            protocol: TCP
          args:
          - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
          - -port=8080
          - -quiet
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: true
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
spec:
  clusterIP: {{kubernetes_dns_service_address}}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    k8s-app: kube-dns
