apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: secrets
    image: {{ .kmsctl_image }}
    args:
    - --region={{ .aws_region }}
    - get
    - --output-dir=/etc/secrets
    - --bucket={{ .secrets_bucket_name }}
    - --sync=true
    - --recursive=true
    - common/kubeconfig_proxy
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 800Mi
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  - name: kube-proxy
    image: {{ .kubernetes_image }}
    command:
    - /hyperkube
    - proxy
    - --cluster-cidr={{ .flannel_cidr }}
    - --kubeconfig=/etc/secrets/kubeconfig_proxy
    - --logtostderr=true
    - --master=https://{{ .kubeapi_dns_name }}
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10249
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        memory: 50Mi
      limits:
        memory: 8000Mi
    volumeMounts:
    - name: certs
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
    - name: dbus
      mountPath: /var/run/dbus
      readOnly: false
  volumes:
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: secrets
    emptyDir: {}
  - name: dbus
    hostPath:
      path: /var/run/dbus
