apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: secrets
    image: {{ .kmsctl_image }}
    args:
    - --region={{ .aws_region }}
    - get
    - --output-dir=/etc/kubernetes
    - --bucket={{ .secrets_bucket_name }}
    - --sync=true
    - --sync-interval=1m
    - --recursive=true
    - secure/
    resources:
      requests:
        memory: 50Mi
      limits:
        memory: 800Mi
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  - name: kube-auth
    image: {{ .kube_auth_image }}
    args:
    - --listen=127.0.0.1:8443
    - --token-file=/etc/secrets/tokens.csv
    - --auth-policy=/etc/secrets/auth-policy.json
    - --tls-cert=/etc/secrets/kubeapi.pem
    - --tls-key=/etc/secrets/kubeapi-key.pem
    resources:
      requests:
        memory: 50Mi
      limits:
        memory: 4000Mi
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
    - name: certs
      mountPath: /etc/ssl/certs
      readOnly: true
  - name: apiserver
    image: {{ .kubernetes_image }}
    command:
    - /hyperkube
    - apiserver
    - --admission-control=AlwaysPullImages,NamespaceLifecycle,LimitRanger,ResourceQuota,ServiceAccount
    - --allow_privileged=true
    - --apiserver-count={{ .kubeapi_count }}
    - --authentication-token-webhook-cache-ttl=1m
    - --authentication-token-webhook-config-file=/etc/secrets/token-webhook.yaml
    - --authorization-mode=Webhook
    - --authorization-webhook-config-file=/etc/secrets/auth-webhook.yaml
    - --audit-log-maxage=3
    - --audit-log-path=/var/log/kubernetes/apiserver-audit.log
    - --cloud-config=/etc/kubernetes/cloud.cfg
    - --cloud-provider=aws
    - --enable-swagger-ui=true
    - --etcd-servers={{ .etcd_memberlist }}
    - --insecure-port=8080
    - --logtostderr=true
    - --runtime-config=authorization.k8s.io/v1beta1=true,rbac.authorization.k8s.io/v1alpha1=true,extensions/v1beta1/networkpolicies=true
    - --secure-port=6443
    - --service-cluster-ip-range=10.200.0.0/16
    - --tls-cert-file=/etc/secrets/kubeapi.pem
    - --tls-private-key-file=/etc/secrets/kubeapi-key.pem
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
    - name: certs
      mountPath: /etc/ssl/certs
      readOnly: true
  volumes:
  - name: secrets
    emptyDir: {}
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: kubernetes
    hostPath:
      path: /etc/kubernetes
