#cloud-config

coreos:
  etcd2:
    proxy: on
    listen-client-urls: https://127.0.0.1:2379
    cert-file: /run/etcd2/etcd.pem
    key-file: /run/etcd2/etcd-key.pem
  flannel:
    interface: $private_ipv4
    etcd_endpoints: https://127.0.0.1:2379
    etcd_cafile: /etc/ssl/etcd/ca.pem
  locksmith:
    endpoint: https://127.0.0.1:2379
  update:
    reboot-strategy: 'off'
  units:
  - name: systemd-sysctl.service
    command: restart
  - name: iptables-restore.service
    enable: true
    command: start
  - name: format-docker-volume.service
    command: start
    content: |
      [Unit]
      Description=Formats the docker volume
      After=dev-xvdd.device
      Requires=dev-xvdd.device
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/bash -c '/usr/sbin/blkid /dev/xvdd || (/usr/sbin/wipefs -f /dev/xvdd && /usr/sbin/mkfs.ext4 /dev/xvdd)'
  - name: var-lib-docker.mount
    command: start
    enable: true
    content: |
      [Unit]
      Description=Mount docker volume
      Requires=format-docker-volume.service
      After=format-docker-volume.service
      Before=docker.service
      [Mount]
      What=/dev/xvdd
      Where=/var/lib/docker
      Type=ext4
  - name: install-etcd-discovery.service
    command: start
    content: |
      [Unit]
      Description=Etcd Discovery Service
      Before=etcd2.service

      [Service]
      RemainAfterExit=yes
      Restart=always
      RestartSec=10
      Environment="URL=${etcd_discovery_url}"
      Environment="FILENAME=/opt/bin/etcd-discovery"
      Environment="FILENAME_GZ=/opt/bin/etcd-discovery.gz"
      Environment="MD5=${etcd_discovery_md5}"
      ExecStartPre=/usr/bin/mkdir -p /opt/bin /etc/sysconfig
      ExecStartPre=-/usr/bin/rm -f /opt/bin/etcd-discovery
      ExecStart=/usr/bin/bash -c 'until [[ -x $${FILENAME} ]] && [[ $(md5sum $${FILENAME} | cut -f1 -d" ") == $${MD5} ]]; \
        do wget -q -O $${FILENAME_GZ} $${URL} && gunzip $${FILENAME_GZ} && chmod +x $${FILENAME}; done'
  - name: etcd-discovery.service
    command: start
    content: |
      [Unit]
      Description=Etcd Discovery Service
      Requires=update-ca-certificates.service
      Requires=install-etcd-discovery.service
      After=update-ca-certificates.service
      After=install-etcd-discovery.service
      Before=etcd2.service

      [Service]
      Type=notify
      NotifyAccess=all
      RemainAfterExit=yes
      Restart=always
      RestartSec=10
      ExecStartPre=/opt/bin/etcd-discovery \
        -scaling-group-name=${secure_asg_name} -proxy-mode=true \
        -environment-file=/etc/sysconfig/etcd-discovery -logtostderr -v=10
      ExecStart=/usr/bin/systemd-notify --ready --status="succussfully performed etcd discovery"
  - name: docker.service
    drop-ins:
    - name: 10-opts.conf
      content: |
        [Service]
        Environment="DOCKER_OPTS=--iptables=false --log-opt max-size=100m --log-opt max-file=1 --default-ulimit=nofile=32768:32768 --default-ulimit=nproc=16384:16384"
  - name: etcd2.service
    command: start
    enable: true
    drop-ins:
    - name: 10-dependencies.conf
      content: |
        [Unit]
        Requires=update-ca-certificates.service
        Requires=etcd-discovery.service
        Requires=install-kmsctl.service
        After=update-ca-certificates.service
        After=etcd-discovery.service
        After=install-kmsctl.service
    - name: 15-kmsctl.conf
      content: |
        [Service]
        RuntimeDirectory=etcd2
        RuntimeDirectoryMode=0700
        EnvironmentFile=/etc/kmsctl
        ExecStartPre=/opt/bin/kmsctl get --output-dir=%t/etcd2 common/etcd.pem common/etcd-key.pem
    - name: 30-etcd_peers.conf
      content: |
        [Service]
        EnvironmentFile=/etc/sysconfig/etcd-discovery
  - name: fleet.service
    enable: false
  - name: flanneld.service
    command: start
    enable: true
    drop-ins:
    - name: 50-network-config.conf
      content: |
        [Service]
        ExecStartPre=/usr/bin/etcdctl --peers https://127.0.0.1:2379 set /coreos.com/network/config '{"Network":"${flannel_cidr}","Backend":{"Type":"aws-vpc"}}'
    - name: 10-env-config.conf
      content: |
        [Service]
        EnvironmentFile=/run/flannel/options.env
  - name: install-kmsctl.service
    command: start
    content: |
      [Unit]
      Description=Install kmsctl
      Documentation=https://github.com/gambol99/kmsctl
      Before=etcd2.service

      [Service]
      Type=notify
      NotifyAccess=all
      RemainAfterExit=yes
      TimeoutStartSec=180
      Environment="URL=${kmsctl_release_url}"
      Environment="FILE=/opt/bin/kmsctl"
      Environment="MD5SUM=${kmsctl_release_md5}"
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/bash -c 'until [[ -x $${FILE} ]] && [[ $(md5sum $${FILE} | cut -f1 -d" ") == $${MD5SUM} ]]; do wget -q -O $${FILE}.gz $${URL} && gunzip $${FILE}.gz && chmod +x $${FILE}; done'
      ExecStart=/usr/bin/systemd-notify --ready --status="succussfully downloaded the kmsctl"
  - name: update-ca-certificates.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Update CA Certificates
      Requires=install-kmsctl.service
      After=install-kmsctl.service
      Before=etcd2.service

      [Service]
      Type=notify
      NotifyAccess=all
      EnvironmentFile=/etc/environment
      EnvironmentFile=/etc/kmsctl
      RemainAfterExit=yes
      TimeoutStartSec=300
      ExecStartPre=/usr/bin/mkdir -p /etc/ssl/etcd
      ExecStartPre=/opt/bin/kmsctl get --output-dir=/etc/ssl/certs common/ca.pem
      ExecStartPre=/usr/bin/cp -f /etc/ssl/certs/ca.pem /etc/ssl/etcd/ca.pem
      ExecStartPre=/usr/sbin/update-ca-certificates
      ExecStart=/usr/bin/systemd-notify --ready --status="succussfully updated the ca root certificates"
  # @TODO - switching the auto-update for now, doesnt work well in a ASG
  - name: update-engine.service
    command: stop
    enable: false
  - name: kubelet.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Kubelet
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes
      Requires=install-kmsctl.service
      Requires=etcd-discovery.service
      After=install-kmsctl.service
      After=etcd-discovery.service

      [Service]
      Restart=always
      RestartSec=10
      RuntimeDirectory=kubelet
      RuntimeDirectoryMode=0700
      Environment=KUBELET_VERSION=${kubernetes_version}
      Environment=KUBELET_ACI=${kubernetes_image}
      Environment="RKT_OPTS=--volume etc-resolv-conf,kind=host,source=/etc/resolv.conf --mount volume=etc-resolv-conf,target=/etc/resolv.conf"
      EnvironmentFile=/etc/kmsctl
      EnvironmentFile=/etc/environment
      EnvironmentFile=/etc/aws-environment

      ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
      ExecStartPre=/opt/bin/kmsctl get -output-dir=%t/kubelet compute/kubeconfig_kubelet compute/kubeconfig_proxy
      ExecStartPre=/opt/bin/kmsctl get -output-dir=/etc/kubernetes/manifests --recursive manifests/compute

      ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --cloud-provider=aws \
        --cloud-config=/etc/kubernetes/cloud.cfg \
        --address=0.0.0.0 \
        --api-servers=${kube_elb_dns_name} \
        --kubeconfig=%t/kubelet/kubeconfig_kubelet \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=${kubernetes_dns_service_address} \
        --cluster-domain=cluster.local \
        --image-gc-high-threshold=60 \
        --image-gc-low-threshold=40 \
        --maximum-dead-containers=10 \
        --maximum-dead-containers-per-container=1 \
        --image-gc-high-threshold=60 \
        --image-gc-low-threshold=40 \
        --cpu-cfs-quota=true \
        --logtostderr=true
write_files:
- path: /etc/kubernetes/cloud.cfg
  permissions: 0444
  owner: root
  content: |
    [Global]
    KubernetesClusterTag = "${platform}"
    DisableSecurityGroupIngress = true
- path: /etc/sysctl.d/10-disable-ipv6.conf
  permissions: 0644
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6 = 1
- path: /var/lib/iptables/rules-save
  content: |
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    -A FORWARD -d 169.254.169.254/32 -i docker0 -p tcp -m tcp -j DROP
    -A FORWARD -i docker0 -p tcp -m tcp --dport 2379 -j DROP
    :OUTPUT ACCEPT [0:0]
    COMMIT

- path: /etc/kmsctl
  content: |
    AWS_S3_BUCKET=${secrets_bucket_name}
    AWS_DEFAULT_REGION=${aws_region}
- path: /etc/aws-environment
  content: |
    AWS_REGION=${aws_region}
    DNS_ZONE_NAME=${dns_zone_name}
    ENVIRONMENT=${environment}
    PLATFORM_NAME=${platform}
