apiVersion: v1
kind: Service
metadata:
  name: kubedns
  namespace: kube-system
  labels:
    name: kubedns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
spec:
  selector:
    name: kubedns
  clusterIP: 10.200.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
